version: '3.8'
services:
  trial:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    environment:
      - DEBUG=true
    image: telyson/trial:0.0.6
